delete from minas_role;

INSERT INTO `minas_role` VALUES ('1', 'Administrator', 'Administrator');
INSERT INTO `minas_role` VALUES ('20', 'Advanced Operator', 'Advanced Operator');
INSERT INTO `minas_role` VALUES ('30', 'Primary Operator', 'Primary Operator');
INSERT INTO `minas_role` VALUES ('40', 'Monitor', 'Monitor');



delete from mcbts_template where moId = -200 or moId = -300 or moId = -400;

INSERT INTO `mcbts_template` (`moId`, `name`, `backupId`, `referredTemplateId`, `referredTemplateName`, `operationName`, `addedTime`, `lastModifiedTime`) VALUES 
('-200','Default Template(V5 BTS)','0','0','',NULL,now(),now()),
('-300','Default Template(DMBT)','0','0','',NULL,now(),now()),
('-400','Default Template(RRU)','0','0','',NULL,now(),now());



delete from sys_properties;

INSERT INTO `sys_properties` (`idx`, `category`, `sub_category`, `property`, `value`, `description`) VALUES 
('1','platform',NULL,'terminal_version_force_update','false','Force Upgrade Switch'),
('2','platform',NULL,'system_freq_switch','0','System Available Frequency Sending Status:0,Full frequency range;1,Scan available freq. set first;2,Scan available freq. set only'),
('3','platform',NULL,'channel_comparable_mode','0','mcbts_channelcomparablemode:0,Only supported the PCCH configuration;1,Only supported the PECCH configuration;2,Supported the PCCH configuration and PECCH configuration'),
('4','platform',NULL,'mcbts_link_sync','true','BTS link synchronized,false:UnSynchronized,true:Synchronized'),
('5','platform',NULL,'simulcast_resource_sync','true','Simulcast Resource Sync,false:UnSynchronized;true:Synchronized'),
('6','platform',NULL,'data_package_filter_mode','0','Data Package Filter Rule,Value is 0,1,2,3'),
('7','platform',NULL,'mcbts_switchoptimize','0','Optimize Switch:0,Disable;1,Enable'),
('8','platform',NULL,'mcbts_preventbroadcast_flowControlSwitch','0','Flow Control Switch:0,Disable;1,Enable'),
('9','platform',NULL,'mcbts_preventbroadcast_MAXBroadcastPackets','10','MAXBroadcastPackets'),
('10','platform',NULL,'mcbts_btsreleasevoicetimer_voicetimer1','30','BTS ReleaseVoiceTimer Voice Timer1'),
('11','platform',NULL,'mcbts_btsreleasevoicetimer_voicetimer2','30','BTS ReleaseVoiceTimer Voice Timer2'),
('101','platform',NULL,'core_net_type','1000','Core network type'),
('201','platform',NULL,'video_config','0,,','Video config'),
('2001','enb',NULL,'mcc','040600','Mobile country code'),
('2002','enb',NULL,'mnc','0000ff','Mobile network code'),
('2003','enb',NULL,'eea','000000','Encryption algorithm'),
('2004','enb',NULL,'eia','000000','Integrity protection algorithm');



delete from terminal_version_type;

INSERT INTO `terminal_version_type` (`id`, `type_name_en`) VALUES ('100000','Modem'), 
('100100','Mobile Phone'), ('100200','PC Card'), ('100300','CPE122'), ('100400','SuperCpe 5MHz'), 
('100600','CPE128'), ('100800','CPE628'), ('101700','RDA Handset'), ('101800','RDA PCMCIA'), 
('101900','CPE123/CPE323/CPE623'), ('102000','RDA 5M SuperCPE'), ('102100','E68'), 
('102200','MEM133'), ('102300','W118'), ('102400','ePST165'), ('102500','CPE828'), 
('103500','CPE501'), ('103700','E68B/E68s'), ('104100','W635'), ('104200','W636'), 
('104300','W660'), ('104400','W160'), ('104500','W118A'), ('104600','MEM160/MEM136'), 
('104700','MEM660/MEM638'), ('104800','ePST681/ePST681A'), ('104900','U28D'), 
('105000','W645'), ('105100','U28'), ('105300','MEM360'), ('105500','CPE722'), 
('105600','SCPE198/SCPE190'), ('105700','SCPE698/SCPE690'), ('105800','SCPE398/SCPE390'), 
('106100','RS3006W-1800M Module'), ('106400','CPE438'), ('106500','CPE438W'), 
('106600','CPE498'), ('106700','U28C'), ('106800','E68C'), ('106900','RS3006W-400M Module'), 
('107000','RS3006W-1800M&400M Testing Module'), ('107100','W360 Mobile Phone'), ('107200','Wi168'), 
('107300','MG638'), ('107400','MG138'), ('107800','MTU638-RG Module'), ('107900','IMEM170FAT Electric Module'), 
('108000','ePST681'), ('108100','MEM660L'), ('108200','MEM113B'), ('108300','Cpe101 Change Freq'), 
('108400','CPE628W'), ('108500','MPE158'), ('108600','MPE658'), ('108700','MT158'), 
('108800','MT358'), ('108900','MT658'), ('109000','Wi368'), ('109100','Wi668/Wi668A'), 
('109200','ePST681'), ('109300','MEMPA400M-1W/4W'), ('109400','MEMPA400M-5W'), 
('109500','CPE700/Wi198'), ('109600','CPE438L'), ('109800','CPE190W'), ('110000','CPE128W'), 
('110100','Wi198'), ('110200','Wi698'), ('110300','Wi398'), ('110400','MPE159'), 
('110500','CPE9623'), ('110600','AMT9610'), ('110700','AMT9620'), ('110800','MEMP660 Embedded Module'), 
('110900','McWiLLMRE340 Auto Repeater'), ('111000','McWiLLMRE400 Auto Repeater'), ('111100','Wi628'), 
('111200','MEMP160'), ('111300','SCPE190'), ('111400','SCPE390'), ('111500','SCPE690'), 
('111600','W128 UT In Hand'), ('111700','MG128 UT In Hand'), ('111800','McWiLL CPE128W Wireless Broadband Access UT'), 
('111900','CPE623Z/CPE123Z Wireless Broadband Access UT'), ('112000','ePST181 Wireless Comprehensive Access Phone'), 
('112100','Wi108 Multi-Media UT In Hand'), ('112200','Wi128 Multi-Media UT In Hand'), 
('112300','McWiLL CPE453W Wireless Broadband Access UT'), ('112400','MZ1104A Wireless Broadband Comprehensive Access Equipment'), 
('112500','AMT630 CarCarried Equipment'), ('112600','AMT130 CarCarried Equipment'), ('112700','W118B Mobile Phone'), 
('112800','Wi118 Multi-Media UT In Hand'), ('112900','Wi618 Multi-Media UT In Hand'), 
('113000','McWiLL CPE128W Wireless Broadband Access UT'), ('113100','MEM933 Wireless Broadband Access Moudle/1M CPE-Z'), 
('113200','Mi108 McWiLL/GSM Double Module Smart Phone/5M CPE-Z'), ('113300','MEM160A Wireless Broadband Access Moudle'), 
('113400','CPE123A Wireless Broadband Access UT'), ('113500','Mi106 McWiLL/GSM Double Module Smart Phone'), 
('113600','400M Matrix Signal Imitate Equiment MTX5000-40'), ('113700','1800M Matrix Signal Imitate Equiment MTX5000-18'), 
('113800','MBT9630 Multi-Media Backpacked UT'), ('114700','RDA 1M CPE-Z'), ('114800','RDA 5M CPE-Z'), 
('116500','E68A');



delete from district where id = 100000000;

INSERT  INTO `district`(`id`,`name`,`type`,`parentId`,`description`) VALUES 
(100000000,'Root',0,-1,'Root District');



-- ---------- Security Management------------

delete from minas_operation;
-- ----------------------------
-- Records of minas_operation
-- ----------------------------
INSERT INTO `minas_operation` VALUES 
('McBtsList', 'McBtsList'),
('SyncFromEMSToNE', 'SyncFromEMSToNE'),
('SyncFromNEToEMS', 'SyncFromNEToEMS'),
('LocationArea', 'LocationArea Management'),
('McBtsTemplateManage', 'McBtsTemplateManagement'),
('CommonChannelConfig', 'CommonChannelConfiguration'),
('McBtsVersionManage', 'McBtsVersionManagement'),
('McBtsBatchUpgrade', 'McBtsBatchUpgrade'),
('TerminalVersionManage', 'TerminalVersionManagement'),
('TerminalVersionForceUpdate', 'TerminalVersionForceUpdate'),
('TerminalTypeManage', 'TerminalTypeManage'),
('DistrictManage', 'DistrictManage'),
('SimulcastManage', 'SimulcastManage'),
('SimulcastResourceSync', 'SimulcastResourceSync'),
('SysEffectiveFreqConfig', 'SysEffectiveFreqConfig'),
('ServiceLevel', 'ServiceLevelConfiguration'),
('DataPackageFilterConfig', 'DataPackageFilterConfiguration'),
('SwitchOptimizeConfig', 'SwitchOptimizeConfiguration'),
('BTSMangeState', 'BTSMangeState'),
('McBtsDiagnosis', 'McBtsDiagnosis'),
('GPSMessageManage', 'GPSMessageManagement'),
('PerfLogConfig', 'PerfLogConfig'),
('BTSRestart', 'BTSRestart'),
('TemperatureWatch', 'TemperatureWatch'),
('TelnetInfo', 'Telnet Info'),
('McBtsSequenceNumber', 'McBtsSequenceNumber'),
('L1Config', 'L1 Config'),
('CalibrationTypeConfig', 'CalibrationTypeConfig'),
('CalibrationDataConfig', 'CalibrationDataConfig'),
('CalibrationRequest', 'CalibrationReques'),
('CalibrationResult', 'CalibrationResult'),
('AntennaLockConfig', 'AntennaLockConfig'),
('AirLink','AirLink'),
('ResManagementConfig', 'ResManagementConfig'),
('N=1ParameterConfig', 'N=1ParameterConfig'),
('ChangeAlgorithmParamConfig', 'ChangeAlgorithmParamConfig'),
('RangingConfig', 'RangingConfig'),
('LoadBalanceConfig', 'LoadBalanceConfig'),
('SDMAConfig', 'SDMAConfig'),
('DataOperation', 'DataOperation'),
('NeighbourListConfig', 'NeighbourListConfig'),
('ACLConfig', 'ACLConfig'),
('RepeaterConfig', 'RepeaterConfig'),
('VLANConfig', 'VLANConfig'),
('TrunkConfig', 'TrunkConfig'),
('WeakFaultConfig', 'WeakFaultConfig'),
('ChargeParamConfig', 'ChargeParamConfig'),
('BackupSAGParameter', 'BackupSAGParameter'),
('WCPEConfig', 'WCPEConfig'),
('RCPEConfig', 'RCPEConfig'),
('DBSServer', 'DBSServer'),
('GPSClock', 'GPSClock'),
('RemoteBtsConfig', 'RemoteBtsConfig'),
('MBMSBtsConfig', 'MBMSBtsConfig'),
('PoticalFrequencyConfig', 'PoticalFrequencyConfig'),
('SysEffectiveFreqPushDown', 'SysEffectiveFreqPushDown'),
('DataPackageFilterPushDown', 'DataPackageFilterPushDown'),
('SwitchOptimizeConfigPushDown', 'SwitchOptimizeConfigPushDown'),
('VerificationConfig', 'VerificationConfig'),
('McBtsSynConfig', 'McBtsSynConfig'),
('McBtsStatusQuery', 'McBtsStatusQuery'),
('McBtsRfPanelStatus', 'McBtsRfPanelStatus'),
('McBtsUserCountsQuery', 'McBtsUserCountsQuery'),
('McBtsOnlineTerminalList', 'McBtsOnlineTerminalList'),
('ForceUTRegister', 'ForceUTRegister'),
('RRUReboot', 'RRUReboot'),
('RRUStatus', 'RRUStatus'),
('RRUSoftwareVersion', 'RRUSoftwareVersion'),
('RRUHardwareInfo', 'RRUHardwareInfo'),
('RRURayModuleInfo', 'RRURayModuleInfo'),
('BBURayModuleInfo', 'BBURayModuleInfo'),
('RRUEnvParamConfig', 'RRUEnvParamConfig'),
('LightAlarmConfig', 'LightAlarmConfig'),
('McBtsVersionDownload', 'McBtsVersionDownload'),
('McBtsVersionUpgrade', 'McBtsVersionUpgrade'),
('TerminalVersionDownload', 'TerminalVersionDownload'),
('UserTerminal', 'UserTerminal'),
('UpgradeUTBootloader', 'UpgradeUTBootloader'),
('UpgradeUTSoftware', 'UpgradeUTSoftware'),
('UTDetective', 'UTDetective'),
('UTRestart', 'UTRestart'),
('UTPerfData', 'UTPerfData'),
('UTMemFunction', 'UTMemFunction'),
('SagManagement', 'SagManagement'),
('CurrentAlarm', 'CurrentAlarm'),
('HistoryAlarm', 'HistoryAlarm'),
('NkList', 'NkList'),
('NkCluster', 'NkCluster'),
('ZkBackup', 'ZkBackup'),
('ZkBackupTask', 'ZkBackupTask'),
('UserManagement', 'UserManagement'),
('KickUser', 'KickUser'),
('UserPassword', 'UserPassword'),
('ChannelComparableMode', 'ChannelComparableMode'),
('T_DEVICE','Device'),
('T_RACK','Rack'),
('T_SHELF','Shelf'),
('T_BOARD','Border'),
('T_TOPO','Topology'),
('T_ENVMON','Environment Monitor'),
('T_ETHPARA','Ethernet Para'),
('T_IPV4','IP Stack V4'),
('T_STROUT','Static Route'),
('T_SCTP','Stream Control Transmission Protocol'),
('T_SNTP','Simple Network Time Protocol'),
('T_OMC','Operation And Maintenance Center'),
('T_SWPKG','Package Of Software'),
('T_SWINFO','Software Information'),
('T_ENB_PARA','ENB Parameter'),
('T_CEL_PARA','Cell Parameter'),
('T_CEL_PUCH','Physical Uplink Channel Parameter'),
('T_CEL_PDCH','Physical Downlink Parameter'),
('T_CEL_PRACH','PRACH Parameter'),
('T_CEL_ULPC','Uplink Power Control Parameter'),
('T_CEL_DLPC','Downlink Power Control Paramter'),
('T_CEL_ALG','Cell Algorithm Parameter'),
('T_CEL_NBRCEL','Neighbour Cell Configuration'),
('T_ENB_MEASCFG','Measurement Configuration'),
('T_ENB_SRVQOS','Qos Parameter'),
('T_ENB_PDCP','PDCP Parameter'),
('T_ENB_RLC','RLC'),
('T_ENB_CTLTMR','L3 Control Timer'),
('T_ENB_UEPARA','UE Parameter'),
('T_ENB_SRVQCI','QCI Parameter'),
('T_ENB_SRVPC','Service Power Control'),
('T_ENB_SRVMAC','Mac Configuration Parameter'),
('T_CEL_RESEL','Cell Reselection Parameter'),
('T_CEL_SISCH','SI Schedul Parameter'),
('T_ENB_CTFREQ','Center Carrier Frequency Configuration'),
('T_CEL_PTT','Cell PTT Parameter'),
('T_CEL_DRX','Cell DRX Parameter'),
('EnbAlarm','EnbAlarm'),
('EnbBasic','EnbBasic'),
('EnbMangeState','EnbMangeState'),
('EnbReset','EnbReset'),
('EnbExportActiveData','EnbExportActiveData'),
('EnbFullTableConfig','EnbFullTableConfig'),
('EnbTimeConfig','EnbTimeConfig'),
('RfSwitchConfig','RfSwitchConfig'),
('EnbSyncFromEMSToNE','Sync from EMS to eNB'),
('EnbSyncFromNEToEMS','Sync from eNB to EMS'),
('ImportEnbData','Import Enb Data'),

('SDCConfig','SDC Config'),
('TcnDatabase','DataBase Backup&Restore'),
('IMSI','IMSI'),
('UserInfo','User Information'),
('UserTemplate','User Template'),
('UserBasicBusiness','User Basic Business'),
('UserCallForwardingBusiness','User Call Forwarding Business'),
('UserStatus','User Status'),
('QoS','QoS'),
('UserIPResource','User IP Resource'),
('UserEmergencyNumber','User Emergency Number'),
('CallingQoS','Calling QoS'),
('BusinessIPQoS','Business IP QoS'),
('VideoMonitorDevice','Video Monitor Device'),
('VideoMonitorNumber','Video Monitor Number'),
('SystemAddress','System Address'),
('SIPRouter','SIP Router'),
('NumberAnalysis','Number Analysis'),
('SystemGlobalConfig','System Global Config'),
('SystemGlobalInfo','System Global Information'),
('MMES1Link','MME S1 Link'),
('MMETAList','MME TA List'),
('SystemEmergencyNumber','System Emergency Number'),
('StaticRouter','Static Router'),
('TcnGlobalRoamInfo','Global Roam Info'),
('TcnVmrLink','Voice and Video Media Recorder'),
('TaList','TA List'),
('SystemGlobalParam','System Parameter Config');

COMMIT;